name: Standup Bot Scheduler

on:
  schedule:
    - cron: '59 23 * * *'    # 11:59 PM (nightly data capture)
    - cron: '00 8 * * *'      # 8:00 AM (morning Teams message)
  workflow_dispatch:          # Manual trigger option

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug directory structure
        run: |
          pwd
          ls -R
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Create credentials
        run: |
          echo "${{ secrets.CREDENTIALS_JSON }}" > credentials.json

      - name: Run Script
        run: python main.py