name: ProjectManagementBot Scheduler

on:
  schedule:
    - cron: '59 23 * * *'   # Extraction cron (UTC)
    - cron: '38 12 * * *'   # Posting cron (UTC)
  workflow_dispatch:         # Manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create credentials.json from secret
        run: |
          printf '%s' "${{ secrets.CREDENTIALS_JSON }}" > credentials.json

      - name: Run the script
        run: python main.py
